service: serverless-pdf-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
package:
  include:
      - fonts/**
functions:
  pdf-generator:
    handler: handler.handler
    timeout: 120
    events:
      - http:
          path: pdf
          method: get
resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"